### ISSUE TITLE
Just looking for an update.

### ISSUE THREAD

**Issue by taboo180** [martok/ImageHash#1]
Hi martok,

Visipics is a favorite of mine so "like visipics but faster" is obviously appealing. Seeing that files have been updated in recent weeks is as well (given Visipics is now nearly a decade without update).

Just wondering if this app can be downloaded as a package anywhere as I'd love to try using it.

Thanks.

**Comment by martok** [comment]
Hi there!
First, how did you even find this repo 😄 
Jokes aside though, yeah, there never has been a public binary release and I would assume I'm the only user. That's kinda reflected in the user interface which is a bit... special and full of debug stuff. The recent changes were mostly me playing with some new ideas, for example.
But sure, if you're interested I can see about getting rid of some hard-coded bits and packaging a binary. It's windows only though as that's what I use, even if large parts should be portable.

**Comment by taboo180** [comment]
Ah thanks so much for replying 😊

I've been using Visipics for _many_ years and every time I reload my PC I download it again and remind myself that it hasn't had an update in a decade. It (to my surprise every time) still functions and works better than any other dupe finder out there, but it's not perfect. And as the internet evolves and my connection gets faster and I accumulate larger image folders to run it on, it is always nice to think "wow, I wish Visipics could run faster".

So I think I found you purely by googleing "Visipics fork" just to see if anyone actually had access to the code and had done anything with it in the last decade.

I believe Visipics isn't open source, so I suspect your app isn't an actual fork, but, I've tried a lot of image dupe finder apps over the years and always come back to Visipics from a usability, quality of life, ease and "just works" perspective.

So! I'd absolutely love to try your app if it doesn't actually cause you more work or put you out in any way. I'd obviously give you all the feedback and my thoughts from a "beta user" perspective if that's what you'd want. Obviously up to you, but I'd really enjoy that 😊

(PS. I am on Windows )

**Comment by taboo180** [comment]
Up to you, but if you'd find chatting easier than using the "issues" form 😅, you can add me on discord - taboo_#4632 or trdtaboo_

**Comment by martok** [comment]
> And as the internet evolves and my connection gets faster and I accumulate larger image folders to run it on, it is always nice to think "wow, I wish Visipics could run faster".

Hehe, true. Overnight scans really didn't seem to make much sense to me around 2019...

> So I think I found you purely by googleing "Visipics fork" just to see if anyone actually had access to the code and had done anything with it in the last decade.

... when I basically did exactly that. Indeed, VisiPics is not open source, and there didn't seem to be an open clone. So I started a project to play around with some image hashes, hence the very creative name. I did *not* expect that the first one I tried (dHash, as linked in the Readme) would be this good.

> [...] from a usability, quality of life, ease and "just works" perspective.

Oh, "usability" is not a point you will apply to this project. It "just works" for me however, but I wrote it, so that's not saying much 😄 

> So! I'd absolutely love to try your app if it doesn't actually cause you more work or put you out in any way.

Well then, I've just published a release with a binary version. I didn't get around to writing documentation, but the important things should look familiar. Basically everything has hint texts that explain what it does, including the more "hidden" features and shortcuts.

The source path input is a bit clunky (the browser always edits the line where the text cursor is), but I actually do use the "just copy and paste multiple paths" so often that I haven't yet replaced it with a more conventional editable list (I really do not like how much clicking that needs in VisiPics).

> I'd obviously give you all the feedback and my thoughts from a "beta user" perspective if that's what you'd want. Obviously up to you, but I'd really enjoy that 😊

For the most part this is really just a toy project I tinker with when something comes up. But sure, let me know if something explodes and we'll see.

**Comment by taboo180** [comment]
Maaaaaate. This is spectacular.

Initial reaction is - It's exactly what it says on the tin - "like Visipics, but faster". I just got through 20,000 pics in <5mins.

I confess, when we first started talking I thought "yeh, it might be 'like visipics' in so much as it's a dupe finder", but it was the way Visipics approached its user experience that I kept coming back to, so I worried that your take would be like many of the other apps out there - can find dupes, but the UX is garbage.

The fact you show the thumbnails like Visipics does. The fact I can just move my mouse over the thumbnails and see  a full preview. The fact I can see crucial info about each pic I'm hovering on like name/size/dimensions. The fact that the only thing I _didn't_ like about Visipics was the "folder selector" as (as you said) it takes too many clicks - and you've addressed that! 😍

Even allowing the user to choose the specific logic of the "automark" tool is a nice touch!

Obviously I haven't had a deep play yet, but it's ticking all my boxes. Thanks man I'll definitely keep using it! I will throw a couple thoughts below too 😊

**Comment by taboo180** [comment]
Separate to all my praise, the only thing that's come up so far as is - out of my 20,000 pics it found ~5000 dupes. I used the automark to select them then hit delete. At that point it's like ImageHash took all my of PC's priority. It didn't show anything like a "deletion progress" bar, and when I tried to click into my other apps that I was working in it was almost like there was an invisible window that was set to "always be on top" because my other apps would flash up for a split second then minimise again. This lasted a few minutes - then my CPU fans span down and I was able to use my other apps again. ImageHash had dissappeared at this point though so I figure it actually crashed out (maybe?, but even if it did there were ~5000 new pics in my recycle bin so it at least did work before crashing ¯\_(ツ)_/¯

I tried again by deleting ~500 pics. This time the ImageHash window stayed open, but if I clicked on it it did the whole "faded not responding" thing that Windows does. So I left it for 20seconds and it all came good with all my pics deleted. It didn't actually crash out or close the ImageHash window this time.

When deleting 140 pics it showed the usual Windows "Sending to recycle bin" progress Window and after that dissappeared the ImageHash window took a couple seconds to remove all the thumbnails and become responsive again.

Either way, just an observation, not a huge issue as it still seems to complete the deleting process. It just seems that while doing so it take a _lot_ of processing power away from everything else.

---

QUALITY OF LIFE OBSERVATIONS:

So, _FULLY_ appreciating that this isn't a product that you're trying to release to market so you have zero obligation to do anything with this info - these are my initial "nice to have" observations.

1) When you hover your mouse on a thumbnail it shows the file path of the image, then size, dimensions and date at the end. When comparing dimensions I might move my mouse over two thumbnails, and because the path length for each is different the size/dimensions/date part jumps all over the place. If you put that info _in front_ of the file name then it would be easier to track with your eyes when comparing two images.

![image](https://github.com/martok/ImageHash/assets/47477508/83e340dd-84d6-4e9f-b362-e7de5c2c24d1)

2) This one's pretty self explanatory, but when using the "automark" window, after the boxes are ticked as desired and you click "mark" have the window auto close as there's nothing else you'd need to do in that window after clicking mark.

![image](https://github.com/martok/ImageHash/assets/47477508/e4465cd7-772d-4163-acf8-3a81ac6c9512)

3) A more visually striking indicator that a thumbnail has been marked for deletion would be nice. Again, super not the end of the world, but the small black and white icon is hard to notice sometimes, especially on small, visually messy, unsaturated images.

![image](https://github.com/martok/ImageHash/assets/47477508/8358a0fd-5ca9-4d70-a591-d1e9d1da7cac)

4) It would also be super nice to have an "open file in Windows explorer" option when right clicking on a thumbnail or something.

5) Super "quality of life" request - but when I scan 1000 images I usually do them on the highest tolerance (0 in this case), then delete all the "true", actual duplicates. Then I increase the tolerance by 1 and run it again to see what files are identical but maybe just a different resolution. Then increase by 1 and run again... etc etc. until I'm around the mid point where images are less duplicates and more just "similar looking" images. What would be really cool is an "increase tolerance by 1 and re-run scan" button. Obviously not essential, but would be a nice "QoL" thing.

6) And finally having an .ini or something to store settings. So if I choose a larger thumbnail size or something it's remembered between sessions 😊

---

PS. Again, I really hope you don't read any of those as demands. I'm already so grateful you gave me a chance to use the app and I honestly can see me using it exclusively for image dupe stuff moving forward in its current state so none of the above will actually stop me using it 😉.

Thanks man. You really did do super great reproducing the ease of use of Visipics but combined with speed.

**Comment by martok** [comment]
Thanks for the feedback! It's always interesting to see what other people immediately run into.

For example I don't think I've ever deleted more than ~100 files. That's clearly a major bug 😄  Tracked as #2.

> 1. When you hover your mouse on a thumbnail it shows the file path of the image, then size, dimensions and date at the end. When comparing dimensions I might move my mouse over two thumbnails, and because the path length for each is different the size/dimensions/date part jumps all over the place. If you put that info _in front_ of the file name then it would be easier to track with your eyes when comparing two images.

I mostly look at the path, that's why that never occured to me. I'll probably just split it on two lines. Tracked as #3.

> 2. This one's pretty self explanatory, but when using the "automark" window, after the boxes are ticked as desired and you click "mark" have the window auto close as there's nothing else you'd need to do in that window after clicking mark.

Yep. #4 .


> 3. A more visually striking indicator that a thumbnail has been marked for deletion would be nice. Again, super not the end of the world, but the small black and white icon is hard to notice sometimes, especially on small, visually messy, unsaturated images.

As you may imagine, I didn't create those, they're from decades-old collections. But yeah, could be better.

> 4. It would also be super nice to have an "open file in Windows explorer" option when right clicking on a thumbnail or something.

Hm, running out of buttons here. Ctrl-MMB maybe?

> What would be really cool is an "increase tolerance by 1 and re-run scan" button. Obviously not essential, but would be a nice "QoL" thing.

Probably not going to happen... it's 2 buttons less than 100px apart...

> 6. And finally having an .ini or something to store settings. So if I choose a larger thumbnail size or something it's remembered between sessions 😊

Hm, maybe. Tracking as #5.

**Comment by taboo180** [comment]
> Probably not going to happen... it's 2 buttons less than 100px apart...

Agreed. _Definitely!_ not essential.

One more observation though. It seems when you "trash" all your marked files, as soon as the deletion process finishes, ImageHash immediately re-runs another scan. So basically the process looks like this: "run Imagehash on 5000 images for a minute. Find 100 duplicates. Auto mark them. Trash them. Wait 10 seconds while Windows deletion window runs. Then as soon as the Windows deletion window finishes, ImageHash takes another few seconds to " re-run" a scan on the 5000 images again.". That last re-run seems unnecessary because you've just deleted all the duplicates so it isn't going to find any more. It's just an extra delay after deletion for no reason (as far as I can tell). 

So either that automatic re-run after a deletion process shouldn't happen. OR! if the auto re-run serves some purpose I don't understand and maybe at this point it should increase the tolerance number by 1 so it at least finds some more duplicates ¯\_(ツ)_/¯

Just a thought.

Anyway man. Thank you so much for your efforts and engaging with my ideas ❤️

**Comment by martok** [comment]
> A more visually striking indicator that a thumbnail has been marked for deletion would be nice. Again, super not the end of the world, but the small black and white icon is hard to notice sometimes, especially on small, visually messy, unsaturated images.

I never particularly liked the full overlays that VisiPics used as they hide so much of the image. When they're not 100% identical anyway you don't really see which one is marked... What I have done is color the images and add a white outline. This should make them stand out on most backgrounds. The ignore mark on the blue-tinted Alyson disappears a bit, but still an improvement.
![image](https://github.com/martok/ImageHash/assets/109197/94801adc-8061-47ee-a251-7b3a89137d6e)
(Bonus in the screenshot: the image currently displayed in the preview now has a focus outline)

> Wait 10 seconds while Windows deletion window runs. Then as soon as the Windows deletion window finishes, ImageHash takes another few seconds to " re-run" a scan on the 5000 images again.".

Technical term here: it's a re-classify, not a re-scan. The classifier is much faster than actually re-scanning anything.
This does indeed have a purpose: depending on the tolerance setting, removing one image could change the clustering of the files in the group it used to be in. Because the "distance" changes, this could in fact create new clusters with images that previously were considered "not duplicates". This is also the reason why it does a full re-classify instead of just looking at the changed clusters again.

I've just released [1.1.0](https://github.com/martok/ImageHash/releases/tag/v1.1.0) with most of those fixed. Thanks again for testing! It's actually funny, even the annoyances that I knew of I would probably never have fixed otherwise 😀

**Comment by taboo180** [comment]
Oh absolutely. Why would you? If the tool was "good enough" and worked for you, you had no one else to impress 😂

I feel bad that I've come along and now gone "that thing you made and has been perfectly fine for years. Yeh, make it better just for me" 😂. But also, I am pretty certain that if a couple other people discover it, it would become a pretty popular tool.

I've really enjoyed discovering it and this little exchange though. So thanks man. I hope it brought you a little fresh enjoyment for your creation too 😊

**Comment by martok** [comment]
> I feel bad that I've come along and now gone "that thing you made and has been perfectly fine for years. Yeh, make it better just for me" 😂

No worries -- it's also better for me 😁

The thing that keeps surprising me is that this tool is over 5 years old (there's some history before the first git revision) and I still keep coming back to it. Most of my stuff gets ADHD'd away much sooner 😅

In any case, I'm going to close this issue as completed for now. If something else comes up, feel free to open a new one!
